<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Tabla_despachos extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tipos = [
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002204001', 'nombre_despacho' => 'DESPACHO 001 DE LA SALA PENAL DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'PLINIO MENDIETA  PACHECO', 'direccion_despacho' => 'Carrera 52 # 42-73 - Palacio De Justicia -la Alpujarra- ', 'telefono_despacho' => '2325560-9879887',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002204002', 'nombre_despacho' => 'DESPACHO 002 DE LA SALA PENAL DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'EDILBERTO ANTONIO  ARENAS CORREA', 'direccion_despacho' => 'Carr 52n°47-73 Piso 27', 'telefono_despacho' => '2325569',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002204003', 'nombre_despacho' => 'DESPACHO 003 DE LA SALA PENAL DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'NANCY  AVILA DE MIRANDA', 'direccion_despacho' => 'Carr 52n°47-73 Piso 27', 'telefono_despacho' => '2325569',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002204004', 'nombre_despacho' => 'DESPACHO 004 DE LA SALA PENAL DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'GUERTHY ACEVEDO ROMERO', 'direccion_despacho' => 'Carr 52n°47-73 Piso 27', 'telefono_despacho' => '2325569',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002204005', 'nombre_despacho' => 'DESPACHO 005 DE LA SALA PENAL DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'RENE  MOLINA  CARDENAS', 'direccion_despacho' => 'Carrera 52#42-73 - Piso 27', 'telefono_despacho' => 'NR',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002204006', 'nombre_despacho' => 'DESPACHO 006 DE LA SALA PENAL DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'GUSTAVO ADOLFO  PINZON  JACOME', 'direccion_despacho' => 'Nr', 'telefono_despacho' => 'NR',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002205001', 'nombre_despacho' => 'DESPACHO 001 DE LA SALA LABORAL DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'NANCY EDITH  BERNAL  MILLAN', 'direccion_despacho' => 'Carrera 52 # 42-73 - Palacio De Justicia -la Alpujarra- ', 'telefono_despacho' => '2325638',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002205002', 'nombre_despacho' => 'DESPACHO 002 DE LA SALA LABORAL DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'HECTOR HERNANDO ALVAREZ  RESTREPO', 'direccion_despacho' => 'Carrera 52 # 42-73 Piso 27', 'telefono_despacho' => '2325638',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002205003', 'nombre_despacho' => 'DESPACHO 003 DE LA SALA LABORAL DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'WILLIAM ENRIQUE  SANTA MARÍN', 'direccion_despacho' => 'Carrera 52 # 42-73 - Palacio De Justicia -la Alpujarra- ', 'telefono_despacho' => '2325638',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002213000', 'nombre_despacho' => 'DESPACHO DE LA SALA CIVIL FAMILIA DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'ANÓNIMO ANÓNIMO', 'direccion_despacho' => 'Nr', 'telefono_despacho' => 'NR-',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'ADMINISTRATIVA' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002213001', 'nombre_despacho' => 'DESPACHO 001 DE LA SALA CIVIL FAMILIA DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'DARIO IGNACIO  ESTRADA  SANIN ', 'direccion_despacho' => 'Carrera 52 # 42-73 - Palacio De Justicia -la Alpujarra- ', 'telefono_despacho' => '2325600',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002213002', 'nombre_despacho' => 'DESPACHO 002 DE LA SALA CIVIL FAMILIA DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'CLAUDIA  BERMUDEZ  CARVAJAL', 'direccion_despacho' => 'Carrera 52 # 42-73 - Palacio De Justicia -la Alpujarra- ', 'telefono_despacho' => '2325654',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'ANTIOQUIA','circuito' => 'ANTIOQUIA (O)','departamento' => 'ANTIOQUIA','municipio' => 'ANTIOQUIA', 'codigo_despacho' => '050002213003', 'nombre_despacho' => 'DESPACHO 003 DE LA SALA CIVIL FAMILIA DEL TRIBUNAL SUPERIOR DE ANTIOQUIA ', 'nombre_juez' => 'OSCAR HERNANDO CASTRO  RIVERA', 'direccion_despacho' => 'Carrera 52 # 42-73 - Palacio De Justicia -la Alpujarra- ', 'telefono_despacho' => '2325654',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013105002', 'nombre_despacho' => 'JUZGADO 002 LABORAL  DE IBAGUÉ ', 'nombre_juez' => 'BLANCA ALEXANDRA SIERRA', 'direccion_despacho' => 'Carrera 2 # 8-90 - Palacio De Justicia ', 'telefono_despacho' => '8-2610060',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013105003', 'nombre_despacho' => 'JUZGADO 003 LABORAL  DE IBAGUÉ ', 'nombre_juez' => 'LUIS ALFREDO CLAROS  MENDEZ', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2614073',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013105004', 'nombre_despacho' => 'JUZGADO 004 LABORAL  DE IBAGUÉ ', 'nombre_juez' => 'ANA MARIA GOMEZ  ESPAÑA', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2617454',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013105005', 'nombre_despacho' => 'JUZGADO 005 LABORAL  DE IBAGUÉ ', 'nombre_juez' => 'ALVARO  CAMPOS  yanguma', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '098-2619451',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013105006', 'nombre_despacho' => 'JUZGADO 006 LABORAL  DE IBAGUÉ ', 'nombre_juez' => 'JEIMMY JULIETH GARZON OLIVERA', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2619304',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013107001', 'nombre_despacho' => 'JUZGADO 001 PENAL DE CIRCUITO ESPECIALIZADO DE IBAGUÉ ', 'nombre_juez' => 'DIEGO FERNANDO CABALLERO PIRABAN', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2623090-',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013107002', 'nombre_despacho' => 'JUZGADO 002 PENAL DE CIRCUITO ESPECIALIZADO DE IBAGUÉ ', 'nombre_juez' => 'CAMILO ANDRES CORTES  COLORADO', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2638069',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013109001', 'nombre_despacho' => 'JUZGADO 001 PENAL DEL CIRCUITO CON FUNCIÓN DE CONOCIMIENTO DE IBAGUÉ ', 'nombre_juez' => 'ISABEL INDIRA  MOLINA ARIZA ', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2617374',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013109002', 'nombre_despacho' => 'JUZGADO 002 PENAL DEL CIRCUITO CON FUNCIÓN DE CONOCIMIENTO DE IBAGUÉ ', 'nombre_juez' => 'HENRY HERNAN BELTRAN  MAYORQUIN', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2614080-',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013109003', 'nombre_despacho' => 'JUZGADO 003 PENAL DEL CIRCUITO CON FUNCIÓN DE CONOCIMIENTO DE IBAGUÉ ', 'nombre_juez' => 'HENRY ALEXANDER FRANCO ARCILA', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2614960',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013109005', 'nombre_despacho' => 'JUZGADO 005 PENAL DEL CIRCUITO CON FUNCIÓN DE CONOCIMIENTO DE IBAGUÉ ', 'nombre_juez' => 'MARTHA YULIETH  OTALORA  RINCON', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2617717',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013109006', 'nombre_despacho' => 'JUZGADO 006 PENAL DEL CIRCUITO CON FUNCIÓN DE CONOCIMIENTO DE IBAGUÉ ', 'nombre_juez' => 'CRISTHIAN CAMILO VALDERRAMA REYES', 'direccion_despacho' => 'Nr', 'telefono_despacho' => 'NR',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013110001', 'nombre_despacho' => 'JUZGADO 001 DE FAMILIA  DE IBAGUÉ ', 'nombre_juez' => 'LUIS CARLOS PRIETO NIVIA', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2623938',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
            ['jurisdiccion' => 'ORDINARIA', 'distrito' => 'IBAGUÉ','circuito' => 'IBAGUÉ','departamento' => 'TOLIMA','municipio' => 'IBAGUÉ', 'codigo_despacho' => '730013110002', 'nombre_despacho' => 'JUZGADO 002 DE FAMILIA  DE IBAGUÉ ', 'nombre_juez' => 'MARCO TULIO GONGORA  MARTINEZ', 'direccion_despacho' => 'Carrera 2 # 8-90', 'telefono_despacho' => '2610943',  'correo_despacho' => 'quiku2021@gmail.com', 'area' => 'JUDICIAL' ], 
        ];
        foreach ($tipos as $key => $value) {
            DB::table('despachos')->insert([
                'jurisdiccion' => $value['jurisdiccion'],
                'distrito' => $value['distrito'],
                'circuito' => $value['circuito'],
                'departamento' => $value['departamento'],
                'municipio' => $value['municipio'],
                'codigo_despacho' => $value['codigo_despacho'],
                'nombre_despacho' => $value['nombre_despacho'],
                'nombre_juez' => $value['nombre_juez'],
                'direccion_despacho' => $value['direccion_despacho'],
                'telefono_despacho' => $value['telefono_despacho'],
                'correo_despacho' => $value['correo_despacho'],
                'area' => $value['area'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
