<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Tabla_Pais extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paises = [
            ['pais' => 'Afganistán', 'nacionalidad' => 'Afgano'],
            ['pais' => 'Albania', 'nacionalidad' => 'Albano'],
            ['pais' => 'Alemania', 'nacionalidad' => 'Alemán'],
            ['pais' => 'Estados Unidos', 'nacionalidad' => 'Americano'],
            ['pais' => 'Andorra', 'nacionalidad' => 'Andorrano'],
            ['pais' => 'Angola', 'nacionalidad' => 'Angolano'],
            ['pais' => 'Antigua y Barbuda', 'nacionalidad' => 'Antiguano'],
            ['pais' => 'Argelia', 'nacionalidad' => 'Argelino'],
            ['pais' => 'Argentina', 'nacionalidad' => 'Argentino'],
            ['pais' => 'Armenia', 'nacionalidad' => 'Armenio'],
            ['pais' => 'Australia', 'nacionalidad' => 'Australiano'],
            ['pais' => 'Austria', 'nacionalidad' => 'Austriaco'],
            ['pais' => 'Azerbaiyán', 'nacionalidad' => 'Azerbaiyano'],
            ['pais' => 'Bahamas', 'nacionalidad' => 'Bahameño'],
            ['pais' => 'Bangladesh', 'nacionalidad' => 'Bangladesí'],
            ['pais' => 'Barbados', 'nacionalidad' => 'Barbadense'],
            ['pais' => 'Bahrein', 'nacionalidad' => 'Bareiní'],
            ['pais' => 'Bélgica', 'nacionalidad' => 'Belga'],
            ['pais' => 'Belice', 'nacionalidad' => 'Beliceño'],
            ['pais' => 'Benin', 'nacionalidad' => 'Beninés'],
            ['pais' => 'Bielorrusia', 'nacionalidad' => 'Bieloruso'],
            ['pais' => 'Birmania, Myanmar', 'nacionalidad' => 'Birmano'],
            ['pais' => 'Bolivia', 'nacionalidad' => 'Boliviano'],
            ['pais' => 'Bosnia-Herzegovina', 'nacionalidad' => 'Bosnio'],
            ['pais' => 'Botswana', 'nacionalidad' => 'Botsuano'],
            ['pais' => 'Brasil', 'nacionalidad' => 'Brasileño'],
            ['pais' => 'Reino Unido', 'nacionalidad' => 'Británico'],
            ['pais' => 'Brunei', 'nacionalidad' => 'Bruneano'],
            ['pais' => 'Bulgaria', 'nacionalidad' => 'Búlgaro'],
            ['pais' => 'Burkina Faso', 'nacionalidad' => 'Burkinés'],
            ['pais' => 'Burundi', 'nacionalidad' => 'Burundés'],
            ['pais' => 'Islas de Cabo Verde', 'nacionalidad' => 'Caboverdiano'],
            ['pais' => 'Camboya', 'nacionalidad' => 'Camboyano'],
            ['pais' => 'Camerún', 'nacionalidad' => 'Camerunés'],
            ['pais' => 'Canadá', 'nacionalidad' => 'Canadiense'],
            ['pais' => 'Qatar', 'nacionalidad' => 'Catarí'],
            ['pais' => 'Sri Lanka', 'nacionalidad' => 'Ceilandés'],
            ['pais' => 'República Centroafricana', 'nacionalidad' => 'Centroafricano'],
            ['pais' => 'Chad', 'nacionalidad' => 'Chadiano'],
            ['pais' => 'Chequia', 'nacionalidad' => 'Checo'],
            ['pais' => 'Chile', 'nacionalidad' => 'Chileno'],
            ['pais' => 'China', 'nacionalidad' => 'Chino'],
            ['pais' => 'Chipre', 'nacionalidad' => 'Chipriota'],
            ['pais' => 'Colombia', 'nacionalidad' => 'Colombiano'],
            ['pais' => 'Comores', 'nacionalidad' => 'Comorense'],
            ['pais' => 'Congo', 'nacionalidad' => 'Congoleño'],
            ['pais' => 'Costa Rica', 'nacionalidad' => 'Costarricense'],
            ['pais' => 'Croacia', 'nacionalidad' => 'Croata'],
            ['pais' => 'Cuba', 'nacionalidad' => 'Cubano'],
            ['pais' => 'Dinamarca', 'nacionalidad' => 'Danés'],
            ['pais' => 'República Dominicana', 'nacionalidad' => 'Dominicano'],
            ['pais' => 'Dominica', 'nacionalidad' => 'Dominiqués'],
            ['pais' => 'Ecuador', 'nacionalidad' => 'Ecuatoriano'],
            ['pais' => 'Egipto', 'nacionalidad' => 'Egipcio'],
            ['pais' => 'Eritrea', 'nacionalidad' => 'Eritreo'],
            ['pais' => 'Eslovaquia', 'nacionalidad' => 'Eslovaco'],
            ['pais' => 'Eslovenia', 'nacionalidad' => 'Esloveno'],
            ['pais' => 'España', 'nacionalidad' => 'Español'],
            ['pais' => 'Estonia', 'nacionalidad' => 'Estonio'],
            ['pais' => 'Etiopía', 'nacionalidad' => 'Etíope'],
            ['pais' => 'Filipinas', 'nacionalidad' => 'Filipino'],
            ['pais' => 'Finlandia', 'nacionalidad' => 'Finés'],
            ['pais' => 'Francia', 'nacionalidad' => 'Francés'],
            ['pais' => 'Gabón', 'nacionalidad' => 'Gabonés'],
            ['pais' => 'Gambia', 'nacionalidad' => 'Gambiano'],
            ['pais' => 'Georgia', 'nacionalidad' => 'Georgiano'],
            ['pais' => 'Ghana', 'nacionalidad' => 'Ghanés'],
            ['pais' => 'Granada', 'nacionalidad' => 'Granadino'],
            ['pais' => 'Chipre (parte Griega)', 'nacionalidad' => 'Greco-Chipriota'],
            ['pais' => 'Grecia', 'nacionalidad' => 'Griego'],
            ['pais' => 'Groenlandia', 'nacionalidad' => 'Groenlandés'],
            ['pais' => 'Guatemala', 'nacionalidad' => 'Guatemalteco'],
            ['pais' => 'Guayana', 'nacionalidad' => 'Guayanés'],
            ['pais' => 'Guinea Ecuatorial', 'nacionalidad' => 'Guineano'],
            ['pais' => 'Guinea', 'nacionalidad' => 'Guineano'],
            ['pais' => 'Guinea-Bissau', 'nacionalidad' => 'Guineano'],
            ['pais' => 'Haití', 'nacionalidad' => 'Haitiano'],
            ['pais' => 'Países Bajos', 'nacionalidad' => 'Holandés'],
            ['pais' => 'Honduras', 'nacionalidad' => 'Hondureño'],
            ['pais' => 'Hungría', 'nacionalidad' => 'Húngaro'],
            ['pais' => 'India', 'nacionalidad' => 'Indio'],
            ['pais' => 'Indonesia', 'nacionalidad' => 'Indionisio'],
            ['pais' => 'Irán', 'nacionalidad' => 'Iraní'],
            ['pais' => 'Irak', 'nacionalidad' => 'Iraquí'],
            ['pais' => 'Irlanda', 'nacionalidad' => 'Irlandés'],
            ['pais' => 'Islandia', 'nacionalidad' => 'Islandés'],
            ['pais' => 'Israel', 'nacionalidad' => 'Israelí'],
            ['pais' => 'Italia', 'nacionalidad' => 'Italiano'],
            ['pais' => 'Jamaica', 'nacionalidad' => 'Jamaicano'],
            ['pais' => 'Japón', 'nacionalidad' => 'Japonés'],
            ['pais' => 'Jordania', 'nacionalidad' => 'Jordano'],
            ['pais' => 'Kazajstán', 'nacionalidad' => 'Kazajo'],
            ['pais' => 'Kenia', 'nacionalidad' => 'Keniata'],
            ['pais' => 'Kirguistán', 'nacionalidad' => 'Kirguís'],
            ['pais' => 'Kiribati', 'nacionalidad' => 'Kiribatiano'],
            ['pais' => 'Kuwait', 'nacionalidad' => 'Kuwaití'],
            ['pais' => 'Laos', 'nacionalidad' => 'Laosiano'],
            ['pais' => 'Lesoto', 'nacionalidad' => 'Lesotense'],
            ['pais' => 'Letonia', 'nacionalidad' => 'Letonio'],
            ['pais' => 'Líbano', 'nacionalidad' => 'Libanés'],
            ['pais' => 'Liberia', 'nacionalidad' => 'Liberiano'],
            ['pais' => 'Libia', 'nacionalidad' => 'Libio'],
            ['pais' => 'Liechtenstein', 'nacionalidad' => 'Liechtensteiniano'],
            ['pais' => 'Lituania', 'nacionalidad' => 'Lituano'],
            ['pais' => 'Luxemburgo', 'nacionalidad' => 'Luxemburgés'],
            ['pais' => 'Macedonia', 'nacionalidad' => 'Macedonio'],
            ['pais' => 'Malaui', 'nacionalidad' => 'Malauí'],
            ['pais' => 'Malasia', 'nacionalidad' => 'Malayo'],
            ['pais' => 'Maldivas', 'nacionalidad' => 'Maldivo'],
            ['pais' => 'Madagascar', 'nacionalidad' => 'Malgache'],
            ['pais' => 'Mali', 'nacionalidad' => 'Maliense'],
            ['pais' => 'Malta', 'nacionalidad' => 'Maltés'],
            ['pais' => 'Costa de Marfil', 'nacionalidad' => 'Marfileño'],
            ['pais' => 'Marruecos', 'nacionalidad' => 'Marroquí'],
            ['pais' => 'Islas Marshall', 'nacionalidad' => 'Marshalés'],
            ['pais' => 'Mauricio', 'nacionalidad' => 'Mauriciano'],
            ['pais' => 'Mauritania', 'nacionalidad' => 'Mauritano'],
            ['pais' => 'México', 'nacionalidad' => 'Mexicano'],
            ['pais' => 'Moldavia', 'nacionalidad' => 'Moldavo'],
            ['pais' => 'Mónaco', 'nacionalidad' => 'Monaqués'],
            ['pais' => 'Mongolia', 'nacionalidad' => 'Mongól'],
            ['pais' => 'Montenegro', 'nacionalidad' => 'Montenegrino'],
            ['pais' => 'Mozambique', 'nacionalidad' => 'Mozambiqueño'],
            ['pais' => 'Namibia', 'nacionalidad' => 'Namibio'],
            ['pais' => 'Nauru', 'nacionalidad' => 'Nauruano'],
            ['pais' => 'Nueva Zelanda', 'nacionalidad' => 'Neozelandés'],
            ['pais' => 'Nicaragua', 'nacionalidad' => 'Nicaraguense'],
            ['pais' => 'Niger', 'nacionalidad' => 'Nigeriano'],
            ['pais' => 'Niue', 'nacionalidad' => 'Niuano'],
            ['pais' => 'Corea del Norte', 'nacionalidad' => 'Norcoreano'],
            ['pais' => 'Noruega', 'nacionalidad' => 'Noruego'],
            ['pais' => 'Omán', 'nacionalidad' => 'Omanés'],
            ['pais' => 'Paquistán', 'nacionalidad' => 'Pakistaní'],
            ['pais' => 'Panamá', 'nacionalidad' => 'Panameño'],
            ['pais' => 'Papúa nueva Guinea', 'nacionalidad' => 'Papú'],
            ['pais' => 'Paraguay', 'nacionalidad' => 'Paraguayo'],
            ['pais' => 'Perú', 'nacionalidad' => 'Peruano'],
            ['pais' => 'Polonia', 'nacionalidad' => 'Polaco'],
            ['pais' => 'Portugal', 'nacionalidad' => 'Portugués'],
            ['pais' => 'Ruanda', 'nacionalidad' => 'Ruandés'],
            ['pais' => 'Rumanía', 'nacionalidad' => 'Rumano'],
            ['pais' => 'Rusia', 'nacionalidad' => 'Ruso'],
            ['pais' => 'Islas Salomón', 'nacionalidad' => 'Salomonense'],
            ['pais' => 'El Salvador', 'nacionalidad' => 'Salvadoreño'],
            ['pais' => 'Samoa', 'nacionalidad' => 'Samoano'],
            ['pais' => 'San Marino', 'nacionalidad' => 'Sanmarinense'],
            ['pais' => 'San Vicente y las Granadinas', 'nacionalidad' => 'Sanvicentino'],
            ['pais' => 'Arabia Saudí, Arabia Saudita', 'nacionalidad' => 'Saudí'],
            ['pais' => 'Senegal', 'nacionalidad' => 'Senegalés'],
            ['pais' => 'Serbia', 'nacionalidad' => 'Serbio'],
            ['pais' => 'Seychelles', 'nacionalidad' => 'Seychelense'],
            ['pais' => 'Sierra Leona', 'nacionalidad' => 'Sierraleonés'],
            ['pais' => 'Singapur', 'nacionalidad' => 'Singapurense'],
            ['pais' => 'Siria', 'nacionalidad' => 'Sirio'],
            ['pais' => 'Somalia', 'nacionalidad' => 'Somalí'],
            ['pais' => 'Suazilandia', 'nacionalidad' => 'Suazi'],
            ['pais' => 'Sudáfrica', 'nacionalidad' => 'Sudafricano'],
            ['pais' => 'Sudán', 'nacionalidad' => 'Sudanés'],
            ['pais' => 'Suecia', 'nacionalidad' => 'Sueco'],
            ['pais' => 'Suiza', 'nacionalidad' => 'Suizo'],
            ['pais' => 'Corea del Sur', 'nacionalidad' => 'Surcoreano'],
            ['pais' => 'Surinam, Suriname', 'nacionalidad' => 'Surinamés'],
            ['pais' => 'Tailandia', 'nacionalidad' => 'Tailandés'],
            ['pais' => 'Tanzania', 'nacionalidad' => 'Tanzano'],
            ['pais' => 'Timor oriental', 'nacionalidad' => 'Timorense'],
            ['pais' => 'Togo', 'nacionalidad' => 'Togolés'],
            ['pais' => 'Tonga', 'nacionalidad' => 'Tongano'],
            ['pais' => 'Túnez', 'nacionalidad' => 'Tunecino'],
            ['pais' => 'Turquía', 'nacionalidad' => 'Turco'],
            ['pais' => 'Tuvalu', 'nacionalidad' => 'Tuvaluano'],
            ['pais' => 'Ucrania', 'nacionalidad' => 'Ucraniano'],
            ['pais' => 'Uganda', 'nacionalidad' => 'Ugandés'],
            ['pais' => 'Uruguay', 'nacionalidad' => 'Uruguayo'],
            ['pais' => 'Uzbekistán', 'nacionalidad' => 'Uzbeco'],
            ['pais' => 'Vanuatu', 'nacionalidad' => 'Vanuatuense'],
            ['pais' => 'Vaticano', 'nacionalidad' => 'Vaticano'],
            ['pais' => 'Venezuela', 'nacionalidad' => 'Venezolano'],
            ['pais' => 'Vietnam', 'nacionalidad' => 'Vietnamita'],
            ['pais' => 'Yemen', 'nacionalidad' => 'Yemení'],
            ['pais' => 'Zambia', 'nacionalidad' => 'Zambiano'],
            ['pais' => 'Zimbabue', 'nacionalidad' => 'Zimbabuense'],



        ];
        foreach ($paises as $item) {
            DB::table('pais')->insert([
                'pais' => utf8_decode(utf8_encode($item['pais'])),
                'nacionalidad' => utf8_decode(utf8_encode($item['nacionalidad'])),
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
