<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Tabla_PQR extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pqrs = [
            ['id'=>'1','radicado'=>'PQR-2023-1','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'1','prioridad_id'=>'2','factura'=>'987654321','fecha_factura'=>'2022-4-10','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-4-16 15:19','fecha_radicado'=>'2023-4-17','fecha_respuesta'=>'NULL','tiempo_limite'=>'22','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'2','radicado'=>'PQR-2023-2','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'21','prioridad_id'=>'2','factura'=>'987654322','fecha_factura'=>'2022-4-12','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-4-19 15:19','fecha_radicado'=>'2022-4-20','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'3','radicado'=>'PQR-2023-3','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'29','prioridad_id'=>'2','factura'=>'987654323','fecha_factura'=>'2022-4-13','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-4-21 15:19','fecha_radicado'=>'2022-4-22','fecha_respuesta'=>'NULL','tiempo_limite'=>'16','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'4','radicado'=>'PQR-2023-4','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'21','prioridad_id'=>'2','factura'=>'987654324','fecha_factura'=>'2022-4-13','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-4-24 15:19','fecha_radicado'=>'2022-4-25','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'5','radicado'=>'PQR-2023-5','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'2','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'30','prioridad_id'=>'2','factura'=>'987654325','fecha_factura'=>'2022-4-13','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-4-26 15:19','fecha_radicado'=>'2022-4-27','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'6','radicado'=>'PQR-2023-6','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'2','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'25','prioridad_id'=>'2','factura'=>'987654326','fecha_factura'=>'2022-4-16','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-4-26 15:19','fecha_radicado'=>'2022-4-27','fecha_respuesta'=>'NULL','tiempo_limite'=>'16','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'7','radicado'=>'PQR-2023-7','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'26','prioridad_id'=>'2','factura'=>'987654327','fecha_factura'=>'2022-4-18','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-4-28 15:19','fecha_radicado'=>'2022-4-29','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'8','radicado'=>'PQR-2023-8','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'17','prioridad_id'=>'2','factura'=>'987654328','fecha_factura'=>'2022-4-18','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-4-28 15:19','fecha_radicado'=>'2022-4-29','fecha_respuesta'=>'NULL','tiempo_limite'=>'16','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'9','radicado'=>'PQR-2023-9','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'23','prioridad_id'=>'2','factura'=>'987654329','fecha_factura'=>'2022-4-21','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-4-29 15:19','fecha_radicado'=>'2022-4-30','fecha_respuesta'=>'NULL','tiempo_limite'=>'16','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'10','radicado'=>'PQR-2023-10','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'30','prioridad_id'=>'2','factura'=>'987654330','fecha_factura'=>'2022-4-22','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-4-29 15:19','fecha_radicado'=>'2022-4-30','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'11','radicado'=>'PQR-2023-11','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'38','prioridad_id'=>'2','factura'=>'987654331','fecha_factura'=>'2022-4-25','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-1 15:19','fecha_radicado'=>'2022-5-2','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'12','radicado'=>'PQR-2023-12','empleado_id'=>'6','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'30','prioridad_id'=>'2','factura'=>'987654332','fecha_factura'=>'2022-4-27','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-3 15:19','fecha_radicado'=>'2022-5-4','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'13','radicado'=>'PQR-2023-13','empleado_id'=>'16','persona_id'=>'4','tipo_pqr_id'=>'2','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'9','prioridad_id'=>'2','factura'=>'987654333','fecha_factura'=>'2022-4-27','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-6 15:19','fecha_radicado'=>'2022-5-7','fecha_respuesta'=>'NULL','tiempo_limite'=>'16','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'14','radicado'=>'PQR-2023-14','empleado_id'=>'16','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'40','prioridad_id'=>'2','factura'=>'987654334','fecha_factura'=>'2022-4-27','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-6 15:19','fecha_radicado'=>'2022-5-7','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'15','radicado'=>'PQR-2023-15','empleado_id'=>'16','persona_id'=>'4','tipo_pqr_id'=>'2','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'22','prioridad_id'=>'2','factura'=>'987654335','fecha_factura'=>'2022-4-28','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-8 15:19','fecha_radicado'=>'2022-5-9','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'16','radicado'=>'PQR-2023-16','empleado_id'=>'16','persona_id'=>'4','tipo_pqr_id'=>'2','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'25','prioridad_id'=>'2','factura'=>'987654336','fecha_factura'=>'2022-5-1','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-8 15:19','fecha_radicado'=>'2022-5-9','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'17','radicado'=>'PQR-2023-17','empleado_id'=>'16','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'4','prioridad_id'=>'2','factura'=>'987654337','fecha_factura'=>'2022-5-1','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-11 15:19','fecha_radicado'=>'2022-5-12','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'18','radicado'=>'PQR-2023-18','empleado_id'=>'16','persona_id'=>'4','tipo_pqr_id'=>'2','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'18','prioridad_id'=>'2','factura'=>'987654338','fecha_factura'=>'2022-5-4','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-14 15:19','fecha_radicado'=>'2022-5-15','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'19','radicado'=>'PQR-2023-19','empleado_id'=>'16','persona_id'=>'4','tipo_pqr_id'=>'2','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'33','prioridad_id'=>'2','factura'=>'987654339','fecha_factura'=>'2022-5-4','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-14 15:19','fecha_radicado'=>'2022-5-15','fecha_respuesta'=>'NULL','tiempo_limite'=>'16','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'20','radicado'=>'PQR-2023-20','empleado_id'=>'17','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'2','prioridad_id'=>'2','factura'=>'987654340','fecha_factura'=>'2022-5-5','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-14 15:19','fecha_radicado'=>'2022-5-15','fecha_respuesta'=>'NULL','tiempo_limite'=>'16','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'21','radicado'=>'PQR-2023-21','empleado_id'=>'17','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'12','prioridad_id'=>'2','factura'=>'987654341','fecha_factura'=>'2022-5-7','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-17 15:19','fecha_radicado'=>'2022-5-18','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'22','radicado'=>'PQR-2023-22','empleado_id'=>'17','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'36','prioridad_id'=>'2','factura'=>'987654342','fecha_factura'=>'2022-5-7','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-17 15:19','fecha_radicado'=>'2022-5-18','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'23','radicado'=>'PQR-2023-23','empleado_id'=>'17','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'38','prioridad_id'=>'2','factura'=>'987654343','fecha_factura'=>'2022-5-8','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-19 15:19','fecha_radicado'=>'2022-5-20','fecha_respuesta'=>'NULL','tiempo_limite'=>'16','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'24','radicado'=>'PQR-2023-24','empleado_id'=>'17','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'23','prioridad_id'=>'2','factura'=>'987654344','fecha_factura'=>'2022-5-9','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-19 15:19','fecha_radicado'=>'2022-5-20','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'25','radicado'=>'PQR-2023-25','empleado_id'=>'17','persona_id'=>'4','tipo_pqr_id'=>'2','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'5','prioridad_id'=>'2','factura'=>'987654345','fecha_factura'=>'2022-5-10','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-22 15:19','fecha_radicado'=>'2022-5-23','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'26','radicado'=>'PQR-2023-26','empleado_id'=>'18','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'14','prioridad_id'=>'2','factura'=>'987654346','fecha_factura'=>'2022-5-12','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-25 15:19','fecha_radicado'=>'2022-5-26','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'27','radicado'=>'PQR-2023-27','empleado_id'=>'18','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'15','prioridad_id'=>'2','factura'=>'987654347','fecha_factura'=>'2022-5-15','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-25 15:19','fecha_radicado'=>'2022-5-26','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'28','radicado'=>'PQR-2023-28','empleado_id'=>'18','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'27','prioridad_id'=>'2','factura'=>'987654348','fecha_factura'=>'2022-5-17','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-27 15:19','fecha_radicado'=>'2022-5-28','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'29','radicado'=>'PQR-2023-29','empleado_id'=>'18','persona_id'=>'4','tipo_pqr_id'=>'2','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'16','prioridad_id'=>'2','factura'=>'987654349','fecha_factura'=>'2022-5-18','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-30 15:19','fecha_radicado'=>'2022-5-31','fecha_respuesta'=>'NULL','tiempo_limite'=>'16','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'30','radicado'=>'PQR-2023-30','empleado_id'=>'18','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'6','prioridad_id'=>'2','factura'=>'987654350','fecha_factura'=>'2022-5-21','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-5-30 15:19','fecha_radicado'=>'2022-5-31','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'31','radicado'=>'PQR-2023-31','empleado_id'=>'19','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'39','prioridad_id'=>'2','factura'=>'987654351','fecha_factura'=>'2022-5-24','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-6-2 15:19','fecha_radicado'=>'2022-6-3','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'32','radicado'=>'PQR-2023-32','empleado_id'=>'19','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'15','prioridad_id'=>'2','factura'=>'987654352','fecha_factura'=>'2022-5-25','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-6-4 15:19','fecha_radicado'=>'2022-6-5','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'33','radicado'=>'PQR-2023-33','empleado_id'=>'19','persona_id'=>'4','tipo_pqr_id'=>'1','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'24','prioridad_id'=>'2','factura'=>'987654353','fecha_factura'=>'2022-5-26','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-6-4 15:19','fecha_radicado'=>'2022-6-5','fecha_respuesta'=>'NULL','tiempo_limite'=>'18','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'34','radicado'=>'PQR-2023-34','empleado_id'=>'19','persona_id'=>'4','tipo_pqr_id'=>'2','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'8','prioridad_id'=>'2','factura'=>'987654354','fecha_factura'=>'2022-5-28','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-6-6 15:19','fecha_radicado'=>'2022-6-7','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],
            ['id'=>'35','radicado'=>'PQR-2023-35','empleado_id'=>'19','persona_id'=>'4','tipo_pqr_id'=>'3','adquisicion'=>'Sede física','sede_id'=>'2','tipo'=>'Producto','referencia_id'=>'15','prioridad_id'=>'2','factura'=>'987654355','fecha_factura'=>'2022-5-29','prorroga'=>'0','prorroga_dias'=>'0','prorroga_pdf'=>'NULL','fecha_generacion'=>'2022-6-7 15:19','fecha_radicado'=>'2022-6-8','fecha_respuesta'=>'NULL','tiempo_limite'=>'17','estado_asignacion'=>'0','estadospqr_id'=>'1','estado_creacion'=>'1','recurso_aclaracion'=>'0','recurso_reposicion'=>'0','recurso_apelacion'=>'0'],



        ];
        foreach ($pqrs as $key => $value) {
            DB::table('pqr')->insert([
                'id' => $value['id'],
                'radicado' => $value['radicado'],
                'empleado_id' => $value['empleado_id'],
                'persona_id' => $value['persona_id'],
                'tipo_pqr_id' => $value['tipo_pqr_id'],
                'adquisicion' => $value['adquisicion'],
                'sede_id' => $value['sede_id'],
                'tipo' => $value['tipo'],
                'referencia_id' => $value['referencia_id'],
                'prioridad_id' => $value['prioridad_id'],
                'factura' => $value['factura'],
                'fecha_factura' => $value['fecha_factura'],
                'prorroga' => $value['prorroga'],
                'prorroga_dias' => $value['prorroga_dias'],
                'prorroga_pdf' => $value['prorroga_pdf'],
                'fecha_generacion' => $value['fecha_generacion'],
                'fecha_radicado' => $value['fecha_radicado'],
                'fecha_respuesta' => $value['fecha_respuesta'],
                'tiempo_limite' => $value['tiempo_limite'],
                'estado_asignacion' => $value['estado_asignacion'],
                'estadospqr_id' => $value['estadospqr_id'],
                'estado_creacion' => $value['estado_creacion'],
                'recurso_aclaracion' => $value['recurso_aclaracion'],
                'recurso_reposicion' => $value['recurso_reposicion'],
                'recurso_apelacion' => $value['recurso_apelacion'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }

    }
}
